# Generated by Django 4.2.11 on 2024-06-24 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markupdate',
            name='mark1',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='markupdate',
            name='mark2',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='markupdate',
            name='mark3',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='markupdate',
            name='mark4',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='markupdate',
            name='mark5',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='markupdate',
            name='mark6',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
